# Generated by Django 5.2.9 on 2025-12-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Store Product - from Meta', 'verbose_name_plural': 'store products - from Meta'},
        ),
    ]
