# Generated by Django 5.2.9 on 2025-12-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='slugT',
        ),
    ]
