# Generated by Django 5.2.9 on 2025-12-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_slug_product_slugt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slugT',
            new_name='slug',
        ),
    ]
