# Generated by Django 5.2.9 on 2025-12-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_collection_product_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='invertory',
            new_name='inventory',
        ),
    ]
