# Generated by Django 5.2.9 on 2025-12-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
