# Generated by Django 5.2.9 on 2025-12-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem", old_name="quatity", new_name="quantity"
        )
    ]
